"""empty message

Revision ID: 0c3e30899544
Revises: d190386b7a87
Create Date: 2021-02-07 02:03:05.867532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3e30899544'
down_revision = 'd190386b7a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion', 'slug',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion', 'slug',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###
