"""empty message

Revision ID: 476a5fe419a8
Revises: 4f1faf4176af
Create Date: 2021-02-07 02:16:26.548942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476a5fe419a8'
down_revision = '4f1faf4176af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion', 'slug',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion', 'slug',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###
